<?php $userId = $this->getRequest()->getParams(); ?>
<?php if(isset($userId['userId'])):?>
<div style= "width:7%" class="seeUsers"><a class="aLink" href="<?php echo $this->getUrl('crud/display/index');?>"> <button class="bButton action primary">Back..</button></a></div>

<div class="page-title-wrapper">
    <h1 class="page-title">
       <span class="base">Welcome...! Please Enter your Address Here...</span>
   </h1>
</div>

<form class="form create account" action="<?php echo $this->getUrl("crud/addressdata/index");?>" method="POST">
    <fieldset class="fieldset ">
        <input type="hidden" name = "addressUserId" class="get-id" value="<?php if(isset($userId['userId'])){ echo $userId['userId']; }?>">
        <div class="field  required">
            <label class="label">
                <span> House No.:</span>
            </label> 
            <div class="control">
                <input required="true" class=" input-text required-entry" placeholder="Enter Flat/House no." type="text" name="houseAdd" value="" minlength="5" maxlength="10">
            </div>
        </div>
        <div class="field  required">
            <label class="label">
                <span>Street:</span>
            </label> 
            <div class="control">
                <input required="true" class="input-text required-entry" placeholder="Enter Your Street" type="text" name="streetAdd" value="" minlength = "5" maxlength="40">
            </div>
        <div>
    </fieldset>
    <fieldset class="fieldset">
        <div class="field  required">
            <label class="label">
                <span>City:</span>
            </label>
            <div class="control"> 
                <input required="true" class="input-text required-entry" placeholder="Enter Your City" type="text" name="cityAdd" value="" minlength = "4" maxlength="15">
            </div>
        </div>
        <div class="field  required">
            <label class="label">
                <span>State:</span>
            </label>
            <div class="control"> 
                <input required="true" class="input-text required-entry" placeholder="Enter Your State" type="text" name="stateAdd" value="" minlength = "4" maxlength="20">
            </div>
        </div>           
        <div class="field required">
            <label class="label">
                <span>pin:</span>
            </label> 
            <div class="control"> 
                <input required="true" class=" input-text" placeholder="Enter Your Pin" type="number" name="pinAdd" value="" minlength = "4" maxlength="6">
            </div>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <button name="addAddress" class="action submit primary" title="Add Address">Add Address</button>
            </div>
        </div>
    </fieldset>
</form>
<?php endif; ?>
